### ISSUE TITLE
Lookup helper bug

### ISSUE THREAD

**Issue by karanpradhan** [jknack/handlebars.java#501] opened 2016-04-16 23:24 UTC
I was trying to use lookup helper as a parameter for passing variables to a partial. However since lookup helper is returning a string I am not able to access the variable as hashmap context in the helper. I think the lookup helper should return a context and not a string.

**Comment by cfinucane** [comment] 2016-05-17 19:50
I am also having this issue, and as demonstrated in #489 this is a divergence from the handlebars.js implementation of the lookup helper.   I tried the naive fix of changing `Helper`s to return `Object`s instead of `CharSequence`s, but this caused some tests to fail, possibly related to string escaping...  haven't had time to dig any further.

**Comment by dontgitit** [comment] 2016-05-18 00:45
this is a duplicate of #489

**Closed** 2016-05-22 21:41 UTC
Labels: enhancement
