### ISSUE TITLE
support passing hash to partials

### ISSUE THREAD

**Issue by mattkime** [jknack/handlebars.java#357] opened 2015-04-07 22:09 UTC
see https://github.com/wycats/handlebars.js/pull/182

support {{> partialName hashKey="foo"}}

(correct me if i'm wrong, but i attempted to use this feature and got an error so i assume its not supported. this is new in handlebars.js 2.0)

**Comment by jfbrennan** [comment] 2015-04-23 00:28
Same problem here, but two things to note:

1) if your NOT using Spring MVC, i.e. you're using Handlebars directly, then you need to do:
new Handlebars( ).withJsFile("handlebars-2.0")

This is because Handlebars.java 2.0 actually defaults to using handlebars.js 1.3 (which seems crazy to me)

2) if you are using Spring like me, then you're totally out of luck for now because the HandlebarsViewResolver just takes the default (1.3) and there's no way to override that. Totally lame and I came here to submit an issue for that.

From what I can tell, Handlebars.java 2.0 is for all intents and purposes still just Handlebars 1.3.

Someone please tell me I'm missing something...

**Comment by jfbrennan** [comment] 2015-04-23 00:34
@jknack this is a duplicate of issue #350

**Comment by jknack** [comment] 2015-04-23 14:23
Guys,

 I will try to find some time and do these changes. I've been busy working on my new project: htttp://jooby.org

 But also, handlebarsjs 1.x has been around for years! and now in just a few month there is a 2.x and 3.x versions :S 
 I'm not saying that is wrong but it is hard to keep track of everything. You I decided to collect new feature request/bugs from handlebars.java users and after that, do the necessarily changes.

 The reason of keep using handlebars 1.3 in handlebars 2.0 was backward compatibility, but I think I will change this in next release.

 @jfbrennan always forgot to update the Spring module :S but you are not lost. There is a workaround:

```java
HandlebarsViewResolver viewResolver = new HandlebarsViewResolver() {
      @Override
      protected Handlebars createHandlebars(URLTemplateLoader templateLoader) {
        Handlebars hbs = super.createHandlebars(templateLoader);
        hbs.withJsFile("...");
        return hbs;
      }
    };
```

Thanks

**Comment by jfbrennan** [comment] 2015-04-23 17:01
Ah, duh! Thanks man

**Comment by jfbrennan** [comment] 2015-04-23 19:03
@mattkime nevermind, I think you already understand what I'm just learning which is that `handlebarsJsFile` is only used for the precompile helper/maven plugin.

**Comment by jknack** [comment] 2015-04-26 17:30
duplicate of #350

**Closed** 2015-04-26 22:53 UTC
Labels: duplicate
